name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: main
    steps:
    - uses: actions/checkout@v3

    - name: Login to Docker Hub
      run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin    
    
    - name: Build the Docker image
      run: |
        terraria_build_version=$(echo {{ vars.TERRARIA_VERSION }} | sed 's|\.||g') \
        docker build . --tag {{ vars.REGISTRY_USER }}/terraria-server:{{ vars.TERRARIA_VERSION }} \
          --build-arg "TERRARIA_VERSION=$terraria_build_version"

    - name: Push the Docker image to Docker Hub
      run: docker push {{ vars.REGISTRY_USER }}/terraria-version:{{ vars.TERRARIA_VERSION }}
