name: Docker Image CI

on:
  workflow_dispatch:
    inputs:
      terrariaVersion:
        description: Version of Terraria server to build
        required: true
env:
  REGISTRY_USER: ${{ secrets.DOCKER_USERNAME }}
  TERRARIA_VERSION: ${{ github.event.inputs.terrariaVersion }}
jobs:
  build:
    runs-on: ubuntu-latest
    environment: main
    steps:
      - uses: actions/checkout@v3

      - name: Login to Docker Hub
        run: echo "${{secrets.DOCKER_PASSWORD }}" | docker login -u "$REGISTRY_USER" --password-stdin

      - name: Build the Docker image
        run: |
          set -e
          terraria_build_version=$(echo $TERRARIA_VERSION | sed 's|\.||g')
          docker build . --tag "$REGISTRY_USER/terraria-server:$TERRARIA_VERSION" \
            --build-arg TERRARIA_VERSION=$terraria_build_version

      - name: Push the Docker image to Docker Hub
        run: docker push "$REGISTRY_USER/terraria-server:$TERRARIA_VERSION"
